name: Upload files to Release (Custom)


on: [ pull_request ] #workflow_dispatch
#  pull_request:
#    types: [ labeled ]
#on:
#  pull_request:
#  schedule:
#    - cron: "0 0 3 * *"

env:
  YEAR: 2022
  MONTH: 10


jobs:
  download:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [ "mania" ]
        fn_version: [ "1000", "10000" ]
    steps:
      - name: Retrieve current dump target file name
        run: |
          echo "FILE_NAME=${{env.YEAR}}_${{env.MONTH}}_01_performance_${{matrix.mode}}_top_${{matrix.fn_version}}" >> $GITHUB_ENV
          echo "Target File Name: ${{ env.FILE_NAME }}"
      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.2.0
        id: tagExists
        with:
          tag: ${{ env.FILE_NAME }}
      - name: Output tag exist check
        run: |
          echo "EXISTS=${{ steps.tagExists.outputs.exists }}" >> $GITHUB_ENV
      - name: Echo if exists
        run: |
          echo Tag ${{ env.EXISTS }}
      - name: Exit Early if exists
        if: ${{ env.EXISTS == true }}
        run: |
          echo exiting
          exit 0
      - name: Test if ran
        run: |
          echo "test"



#      - uses: actions/checkout@v3
#      - name: Set up Python 3.8
#        uses: actions/setup-python@v3
#        with:
#          python-version: "3.8"
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install tables
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: Process data from https://data.ppy.sh with Python
#        run: |
#          python main.py $FILE_NAME
#      - name: Upload binaries to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file_glob: true
#          file: "data/**/csv.tar.gz"
#          release_name: ${{ env.FILE_TARGET }}
#          tag: ${{ env.FILE_TARGET }}
#          overwrite: true
