name: Upload files to GCS

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true
    - name: Deploy
      run: |-
        gsutil -m rsync -R src gs://${{ secrets.GCS_BUCKET }}
